### ISSUE TITLE
Politically correct license description

### ISSUE THREAD

**Issue by xloem** [salesforce/CodeRL#1]
Hi,

I noticed in the README that a handful of licenses are described as the ones that "at least permit academic use". This doesn't look correct to me; I think maybe some information may have been lost in translation. The licenses listed are ones that permit use in closed-source software. In my country, academic works are usually open source.

It would be polite to people who use copyleft licenses (which require works to be open source and are intended to permit academic use, such as the GPL), if the text were to be clarified.

Aside from that, this work is incredibly inspiring and groundbreaking, and thank you so much for publishing it.

**Comment by henryhungle** [comment]
Thanks for your suggestion. We have modified our text in README to make it clearer about the license description.
