### ISSUE TITLE
Does `Trainer_Critic` class mimic `transformers`'s `Trainer` class?

### ISSUE THREAD

**Issue by cwarny** [salesforce/CodeRL#14]
At first glance, it seems like the `Trainer_Critic` class mimic the `transformer` library's `Trainer` class. I'm just curious why you felt the need to do that instead of just using the `Trainer` class?

**Comment by henryhungle** [comment]
@cwarny This trainer critic was modified to include the inputs of test outcome annotations and facilitate tracking of prediction accuracies during training a critic model. Specifically, we mainly modified here https://github.com/salesforce/CodeRL/blob/b3e2ac96e1f0a3cf56ba41965686811ab626c5e6/trainers/trainer_critic.py#L1963-L1968

and here for the new tracking accuracy variable to log the training progress
https://github.com/salesforce/CodeRL/blob/b3e2ac96e1f0a3cf56ba41965686811ab626c5e6/trainers/trainer_critic.py#L1268

The original code of T5 model and trainer do not specifically facilitate this type of classification task so we included the modified code here.
