### ISSUE TITLE
Run generate.py with the CodeT5-large trained on the ground-truth programs

### ISSUE THREAD

**Issue by doviettung96** [salesforce/CodeRL#18]
Hi @henryhungle ,
While waiting for the release of the final RL-finetuned code generator, I would like to run the generator trained on ground-truth programs like [here](https://github.com/salesforce/CodeRL#finetuning-with-ground-truth-programs).
However, the training script `scripts/train_actor.sh` only returns checkpoints. When I check each of the checkpoints, each folder does not have the same files as in the pre-trained model folders. 
So the question is: How can I generate programs from those checkpoints?
Thank you.

**Comment by doviettung96** [comment]
Yeah. I did replace that path in the `generate.sh` script. However, while I'm loading that checkpoint as a generator model ```Loading model from /exps/checkpoints/checkpoint-293000...```
, I got this error:
```OSError: We couldn't connect to 'https://huggingface.co/' to load this model and it looks like /exps/checkpoints/checkpoint-293000 is not the path to a directory conaining a config.json file.```
As I described before, the checkpoint only has `pytorch_model.bin` but not the config.json.
Can I find it anywhere? Or I think I can copy the config.json from `CodeT5-large`, right?
Thanks.

**Comment by henryhungle** [comment]
I am not sure why the `config.json` is not in the checkpoint folder. Is the above connection issue causing this problem? Have you tried to resolve it first? 

I ran using the current code and the training worked fine and `config.json` were saved in checkpoint folders.

**Comment by doviettung96** [comment]
Oh yeah. My bad. It is because I set the path for the checkpoint not quite correctly. It works now. Thank you.
