### ISSUE TITLE
exception of run_unit_tests.sh

### ISSUE THREAD

**Issue by qfzhu** [salesforce/CodeRL#19]
Some synthesized programs got the following exceptions when they are evaluated by the run_unit_test.sh, is there any suggestions? Thanks.

  0% 0/20 [00:00<?, ?it/s]test framework exception = AttributeError("module 'tmp_sol' has no attribute 'zeroes '")module 'tmp_sol' has no attribute 'zeroes '

**Comment by henryhungle** [comment]
@qfzhu Sorry for the late reply! To replicate the issue, can you provide some sample synthesized programs that led to the above error?
