### ISSUE TITLE
Finetuned model checkpoints

### ISSUE THREAD

**Issue by boblee22** [salesforce/CodeRL#2]
Hi,

Thanks for your amazing work! When do you plan to release finetuned model checkpoints?

Thank you very much!

**Comment by doviettung96** [comment]
Yeah. I have the same concern. Thanks.

**Comment by odellus** [comment]
Especially interested in the critic weights as well.

**Comment by henryhungle** [comment]
Sorry for the late response!

We recently released the critic weights and related training/inference processes. 

We will release the other model checkpoints soon! Will update again.

**Comment by parshinsh** [comment]
@henryhungle Thanks for the great work! any update on the finetuned model checkpoints?

**Comment by MT010104** [comment]
@henryhungle Any update on the finetuned model checkpoints?

**Comment by MT010104** [comment]
@henryhungle Any update on the finetuned model checkpoints?

**Comment by henryhungle** [comment]
@MT010104 @parshinsh @doviettung96 @boblee22 @odellus We released the latest model checkpoint of CodeT5 finetuned using the CodeRL framework [here](https://console.cloud.google.com/storage/browser/sfr-coderl-research/codet5_finetuned_codeRL).

Thank you for your patience.

**Comment by qfzhu** [comment]
@henryhungle Thanks for the great work! Is there any update on the code of CodeRL fine-tuning?

**Comment by doviettung96** [comment]
@henryhungle Thank you very much.

**Comment by LJX1888-a** [comment]
@henryhungle Currently, there is a permission access issue when accessing the model checkpoint on Google Drive. The author needs to grant sufficient permissions. Thank you.

**Comment by LJX1888-a** [comment]
@odellus @qfzhu @doviettung96 @MT010104 @henryhungle Do you have model checkpoints? I'm encountering permission issues accessing the project's Google Drive; the author hasn't granted access, so I'd like to download them from you. Thank you.
